services:
  postgres:
    image: postgres:16-alpine
    container_name: poc_mice_postgres
    environment:
      POSTGRES_USER: mice
      POSTGRES_PASSWORD: mice_dev
      POSTGRES_DB: mice_poc
    ports:
      - "5433:5432"
    volumes:
      - poc_mice_pgdata:/var/lib/postgresql/data

volumes:
  poc_mice_pgdata:
